// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9m2NKSrTEOghxrD_r0qkZOHlqerPRehk',
    appId: '1:783229758718:web:254f876a2cd17abf5249af',
    messagingSenderId: '783229758718',
    projectId: 'sistema-pnsa',
    authDomain: 'sistema-pnsa.firebaseapp.com',
    storageBucket: 'sistema-pnsa.firebasestorage.app',
    measurementId: 'G-JTM1QS982K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5CsP8saC3WNPOprO-osoBf2vhHXhAGQ',
    appId: '1:783229758718:android:da863a44c49569045249af',
    messagingSenderId: '783229758718',
    projectId: 'sistema-pnsa',
    storageBucket: 'sistema-pnsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi02HYoGvoV30JjgB4bUE_lvLOsyjxNRs',
    appId: '1:783229758718:ios:2210c3e11a2364425249af',
    messagingSenderId: '783229758718',
    projectId: 'sistema-pnsa',
    storageBucket: 'sistema-pnsa.firebasestorage.app',
    iosBundleId: 'com.example.plataformaPnsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi02HYoGvoV30JjgB4bUE_lvLOsyjxNRs',
    appId: '1:783229758718:ios:2210c3e11a2364425249af',
    messagingSenderId: '783229758718',
    projectId: 'sistema-pnsa',
    storageBucket: 'sistema-pnsa.firebasestorage.app',
    iosBundleId: 'com.example.plataformaPnsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9m2NKSrTEOghxrD_r0qkZOHlqerPRehk',
    appId: '1:783229758718:web:594a345b7d5e1f135249af',
    messagingSenderId: '783229758718',
    projectId: 'sistema-pnsa',
    authDomain: 'sistema-pnsa.firebaseapp.com',
    storageBucket: 'sistema-pnsa.firebasestorage.app',
    measurementId: 'G-X9MGC5G7QG',
  );
}
