// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFRaGH3OY9yq4UC_Zx-wiifpt1x5QHl4',
    appId: '1:471291795710:web:a41cf3f19cd6c96f15adaf',
    messagingSenderId: '471291795710',
    projectId: 'plataforma--pnsa',
    authDomain: 'plataforma--pnsa.firebaseapp.com',
    storageBucket: 'plataforma--pnsa.firebasestorage.app',
    measurementId: 'G-YPMKYBVY39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCmKlWScLOd5qqCkf9U6vbZX7bydSfjdo',
    appId: '1:471291795710:android:dc9b392503f637c215adaf',
    messagingSenderId: '471291795710',
    projectId: 'plataforma--pnsa',
    storageBucket: 'plataforma--pnsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GGmiHRRC8CoLwQkrrI6Dp0cq-SO_F84',
    appId: '1:471291795710:ios:23399c8b1d9197d815adaf',
    messagingSenderId: '471291795710',
    projectId: 'plataforma--pnsa',
    storageBucket: 'plataforma--pnsa.firebasestorage.app',
    iosBundleId: 'com.example.plataformaPnsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9GGmiHRRC8CoLwQkrrI6Dp0cq-SO_F84',
    appId: '1:471291795710:ios:23399c8b1d9197d815adaf',
    messagingSenderId: '471291795710',
    projectId: 'plataforma--pnsa',
    storageBucket: 'plataforma--pnsa.firebasestorage.app',
    iosBundleId: 'com.example.plataformaPnsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIFRaGH3OY9yq4UC_Zx-wiifpt1x5QHl4',
    appId: '1:471291795710:web:0851d6eee053a7eb15adaf',
    messagingSenderId: '471291795710',
    projectId: 'plataforma--pnsa',
    authDomain: 'plataforma--pnsa.firebaseapp.com',
    storageBucket: 'plataforma--pnsa.firebasestorage.app',
    measurementId: 'G-93BHH6CSRY',
  );
}
